export const LOGIN_USER_API = "LOGIN_USER_API";
export const STORE_USER_REDUCER = "STORE_USER_REDUCER";


// ----- JIRA API CONSTANTS -----
export const GET_ALL_CATEGORY_API = "GET_ALL_CATEGORY_API";
export const STORE_CATEGORY = "STORE_CATEGORY";