export const LOGIN_USER_API = "LOGIN_USER_API";
export const STORE_USER_REDUCER = "STORE_USER_REDUCER";
export const STORE_MEMBER_LIST = "STORE_MEMBER_LIST";

// ------- FOR MODAL --------
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_EDIT_FORM = "OPEN_EDIT_FORM";
export const SUBMIT_EDIT_FORM = "SUBMIT_EDIT_FORM";
export const SET_SUBMIT_EDIT_FORM = "SET_SUBMIT_EDIT_FORM";
export const BINDING_PROJECT_TO_REDUX ="BINDING_PROJECT_TO_REDUX";
export const STORE_PROJECT_INFO = "STORE_PROJECT_INFO";

//========== CREATE TASK FORM ========
export const OPEN_CREATE_TASK_FORM = "OPEN_CREATE_TASK_FORM";
export const GET_TASK_TYPE = "GET_TASK_TYPE";
export const STORE_TASK_TYPE = "STORE_TASK_TYPE";
export const GET_PRIORITY_LIST = "GET_PRIORITY_LIST";
export const STORE_PRIORITY_LIST = "STORE_PRIORITY_LIST";
export const CREATE_NEW_TASK = "CREATE_NEW_TASK";
export const SET_SUBMIT_NEW_TASK = "SET_SUBMIT_NEW_TASK"
export const GET_ALL_TASK_STATUS = "GET_ALL_TASK_STATUS";
export const STORE_ALL_TASK_STATUS = "STORE_ALL_TASK_STATUS";
export const GET_TASK_DETAIL_BY_ID = "GET_TASK_DETAIL_BY_ID";
export const STORE_TASK_DETAIL = "STORE_TASK_DETAIL";

// ----- JIRA API CONSTANTS -----
export const GET_ALL_CATEGORY_API = "GET_ALL_CATEGORY_API";
export const STORE_CATEGORY = "STORE_CATEGORY";
export const SUBMIT_NEW_PROJECT = "SUBMIT_NEW_PROJECT";
export const SUBMIT_NEW_PROJECT_WITH_AUTHORISATION = "SUBMIT_NEW_PROJECT_WITH_AUTHORISATION";
export const SUBMIT_EDITING_PROJECT = "SUBMIT_EDITING_PROJECT";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS"; // for Jira
export const STORE_ALL_PROJECTS = "STORE_ALL_PROJECTS";// for redux store
export const DELETE_PROJECT = "DELETE_PROJECT";
export const SHOW_SUCCESS_NOTIFICATION = "SHOW_SUCCESS_NOTIFICATION";
export const GET_ALL_MEMBERS = "GET_ALL_MEMBERS";
export const ASSIGN_MEMBERS_TO_PROJECT = "ASSIGN_MEMBERS_TO_PROJECT";

//DELETE MEMBER FROM PROJECT 
export const DELETE_MEMBER_FORM_PROJECT = "DELETE_MEMBER_FORM_PROJECT";


// PROJECT JIRA ACTION
export const GET_PROJECT_INFO_BY_ID = "GET_PROJECT_INFO_BY_ID";

// UPDATE TASK DETAIL
export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_PRIORITY = "UPDATE_PRIORITY";
export const UPDATE_ESTIMATE_TIME = "UPDATE_ESTIMATE_TIME";
export const UPDATE_DESCRIPTION = "UPDATE_DESCRIPTION";
export const UPDATE_ASSIGNESS = "UPDATE_ASSIGNESS";
export const REMOVE_ASSIGNESS = "REMOVE_ASSIGNESS";


export const UPDATE_STATUS_TO_API = "UPDATE_STATUS_TO_API";
export const UPDATE_DESCRIPTION_TO_API = "UPDATE_DESCRIPTION_TO_API"


